repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.5.0
    hooks:
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-toml
    - id: debug-statements
-   repo: local
    hooks:
    - id: black
      name: black
      entry: poetry run black
      language: system
      types: [python]
      args: [--skip-string-normalization]
    - id: pylint
      name: pylint
      entry: poetry run pylint
      language: system
      types: [python]
